import React, { useCallback, useEffect, useState } from 'react';
import { Alert, Linking, AppState, ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View, useColorScheme } from 'react-native';
import { apiFetch } from '@/store/api';
import { router, useFocusEffect } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

type Provider = { id: string; label: string; kind: string; fields: string[] };
type Source = { id: string; label: string; enabled: boolean; conflicts: number };
type Connection = { id: string; label: string; provider: string; state: string; error_code: string; last_success: string | null; sources: Source[] };
type Listing = { providers: Provider[]; connections: Connection[]; can_manage: boolean; members?: {id:string;label:string}[] };
type Schema = { statuses: { id: string; label: string; field?: string; type?: string }[]; fields: { id: string; type: string }[] };
type Config = { assignees: Record<string,string>; scope: string; fields: Record<string,string>; statusMap: Record<string,string>; writeMap: Record<string,string>; externalUserId: string; statusType: string; includeCompleted: boolean; pastDays: number; futureDays: number; exports: string[] };
const initial: Config = { assignees:{}, scope:'mine', fields:{}, statusMap:{}, writeMap:{}, externalUserId:'', statusType:'status', includeCompleted:false, pastDays:30, futureDays:365, exports:['meetings'] };
const statusOptions = [{id:'todo',label:'До роботи'},{id:'in_progress',label:'У процесі'},{id:'done',label:'Виконано'}];
const labels: Record<string,string> = { host:'Адреса сервісу', email:'Пошта', key:'Ключ API', token:'Токен доступу', password:'Пароль застосунку iCloud', access_token:'Токен Google', refresh_token:'Токен оновлення Google' };
const states: Record<string,string> = {draft:'Потрібне налаштування',active:'Увімкнено',retry:'Повтор синхронізації',attention:'Потрібна увага',disconnected:'Відключено'};

const conflictLabels: Record<string,string> = {state:'Статус',status:'Статус',kanbanColumnId:'Етап',title:'Назва',description:'Опис',start:'Початок',end:'Завершення',location:'Місце',externalRecurrence:'Повторення',cancelled:'Скасування',deadline:'Дата події'};
function conflictText(data:Record<string,unknown>,keys:string[]) { return keys.map(key=>{ let value=data[key]; if(key==='state') value=data.status==='done'?'Виконано':data.kanbanColumnId==='status-in-progress'?'У процесі':'До роботи'; if(key==='deadline') value=data.start; if(value && typeof value==='object' && !Array.isArray(value)) { const date=value as Record<string,unknown>; value=date.dateTime||date.date||'—'; } if(Array.isArray(value))value=value.join(', '); if(typeof value==='boolean')value=value?'Так':'Ні'; return `${conflictLabels[key]||key}: ${value??'—'}`; }).join(' · '); }

export function IntegrationsScreen({projectId,mode='overview'}:{projectId?:string;mode?:'overview'|'settings'}) {
  const settings=mode==='settings', insets=useSafeAreaInsets();
  const overviewHref=projectId?`/project/${encodeURIComponent(projectId)}/integrations`:'/integrations';
  const dark=useColorScheme()==='dark', text=dark?'#f5f3ff':'#201a30', panel=dark?'#201b2c':'#fff';
  const [reconnecting,setReconnecting]=useState<Connection|null>(null),[assignees,setAssignees]=useState<string[]>([]);
  const [listing,setListing]=useState<Listing|null>(null),[provider,setProvider]=useState(''),[credentials,setCredentials]=useState<Record<string,string>>({});
  const [history,setHistory]=useState<{connection:Connection;runs:{id:string;started_at:string;error_code:string}[];conflicts:{id:string;conflict:{fields:string[];local:Record<string,unknown>;remote:Record<string,unknown>}}[]}|null>(null);
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [selected,setSelected]=useState<Connection|null>(null),[available,setAvailable]=useState<{id:string;label:string}[]>([]),[sourceId,setSourceId]=useState('');
  const [schema,setSchema]=useState<Schema|null>(null),[config,setConfig]=useState<Config>(initial);
  const [preview,setPreview]=useState<{token:string;count:number;assignees:string[];outbound:{id:string;title:string}[];items:{id:string;title:string}[]}|null>(null);
  const load=useCallback(async()=>setListing(await apiFetch<Listing>(`/integrations/${projectId?`?project=${encodeURIComponent(projectId)}`:''}`)),[projectId]);
  useFocusEffect(useCallback(()=>{void load().catch(e=>setError(String(e)));},[load]));
  useEffect(()=>{const listener=AppState.addEventListener('change',state=>{if(state==='active')void load().catch(e=>setError(String(e)));});return()=>listener.remove();},[load]);
  const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
  const button=(label:string,action:()=>void,active=false)=><Pressable key={label} accessibilityRole="button" accessibilityState={{disabled:busy,selected:active}} disabled={busy} onPress={action} style={[s.button,{backgroundColor:active?'#7C3AED':dark?'#30243e':'#f2eaff'}]}><Text style={{color:active?'white':dark?'#c7a4ff':'#6231ac',fontWeight:'600'}}>{label}</Text></Pressable>;
  const input=(label:string,value:string,onChange:(v:string)=>void,secret=false)=><View key={label} style={s.field}><Text style={{color:text}}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={onChange} secureTextEntry={secret} autoCapitalize="none" autoCorrect={false} style={[s.input,{color:text,borderColor:dark?'#574367':'#d5c9e4'}]}/></View>;
  const patch=(v:Partial<Config>)=>{setConfig(c=>({...c,...v}));setPreview(null);};
  const choose=async(c:Connection)=>{setHistory(null);setAssignees([]);setSelected(c);setSchema(null);setPreview(null);setConfig({...initial,scope:projectId?'all':'mine'});setAvailable((await apiFetch<{sources:{id:string;label:string}[]}>(`/integrations/${c.id}/sources/`)).sources);};
  const chosenProvider=listing?.providers.find(p=>p.id===provider);
  const calendar=listing?.providers.find(p=>p.id===selected?.provider)?.kind==='calendar';
  return <ScrollView contentContainerStyle={[s.root,{backgroundColor:dark?'#14101b':'#f7f4fb',paddingTop:insets.top+16}]} keyboardShouldPersistTaps="handled">
    <Text accessibilityRole="header" style={[s.title,{color:text}]}>{settings?"Налаштування інтеграцій":"Інтеграції"}</Text><Text style={{color:text}}>{projectId?'Джерела завдань і календарі команди':'Ваші зовнішні завдання й календарі'}</Text>
    {(settings||listing?.can_manage)&&button(settings?'← До інтеграцій':'Налаштування інтеграцій',()=>settings?router.replace(overviewHref as never):router.push(`${overviewHref}/settings` as never))}
    {settings&&listing&&!listing.can_manage&&<Text style={{color:text}}>Налаштування доступні власнику або менеджеру проєкту.</Text>}
    {busy&&<ActivityIndicator accessibilityLabel="Виконується дія" color="#7C3AED"/>}{!!error&&<Text accessibilityRole="alert" style={s.error}>{error}</Text>}{!!notice&&<Text accessibilityLiveRegion="polite" style={{color:text}}>{notice}</Text>}
    {settings&&listing?.can_manage&&<View style={[s.card,{backgroundColor:panel}]}><Text style={[s.heading,{color:text}]}>{reconnecting?`Відновити: ${reconnecting.label}`:"Нове підключення"}</Text><View style={s.row}>{listing.providers.map(p=>button(p.label,()=>{setReconnecting(null);setProvider(p.id);setCredentials({});},provider===p.id))}</View>{chosenProvider?.fields.filter(()=>provider!=='google').map(key=>input(labels[key]||key,credentials[key]||'',v=>setCredentials(c=>({...c,[key]:v})),!['host','email'].includes(key)))}{provider&&button('Підключити',()=>void run(async()=>{if(provider==='google'){const r=await apiFetch<{url:string}>('/integrations/oauth/google/start/',{method:'POST',body:{project:projectId,connection:reconnecting?.id}});await Linking.openURL(r.url);return;}const c=await apiFetch<Connection>(reconnecting?`/integrations/${reconnecting.id}/reconnect/`:'/integrations/',{method:'POST',body:{provider,credentials,project:projectId}});setCredentials({});setProvider('');setReconnecting(null);await load();await choose(c);} ))}<Text style={{color:text,fontSize:12}}>Дані доступу зберігаються зашифрованими на сервері.</Text></View>}
    {listing?.connections.length===0&&<Text style={{color:text}}>Підключень поки немає.</Text>}
    {listing?.connections.map(c=><View key={c.id} style={[s.card,{backgroundColor:panel}]}><Text style={[s.heading,{color:text}]}>{c.label}</Text><Text style={{color:text}}>{states[c.state]||c.state}</Text>{c.last_success&&<Text style={{color:text,fontSize:12}}>Оновлено: {new Date(c.last_success).toLocaleString()}</Text>}{!!c.error_code&&<Text style={s.error}>Перевірте доступ і правила синхронізації.</Text>}{c.sources.map(source=><Text key={source.id} style={{color:text}}>{source.label} · {source.enabled?'Увімкнено':'Очікує підтвердження'}</Text>)}{settings&&listing.can_manage&&button('Відновити доступ',()=>{setReconnecting(c);setProvider(c.provider);setCredentials({});setNotice('Введіть нові дані доступу у формі вище.');})}{listing.can_manage&&c.state!=='disconnected'&&<View style={s.row}>{button('Історія',()=>void run(async()=>{const r=await apiFetch<{runs:{id:string;started_at:string;error_code:string}[];conflicts:{id:string;conflict:{fields:string[];local:Record<string,unknown>;remote:Record<string,unknown>}}[]}>(`/integrations/${c.id}/history/`);setSelected(null);setHistory({connection:c,...r});}))}{settings&&button('Налаштувати',()=>void run(()=>choose(c)))}{button('Оновити',()=>void run(async()=>{await apiFetch(`/integrations/${c.id}/sync/`,{method:'POST'});setNotice('Синхронізацію поставлено в чергу.');}))}{settings&&button('Відключити',()=>Alert.alert('Відключити інтеграцію?','Отримані дані залишаться у Flowi, дані доступу буде видалено.',[{text:'Скасувати',style:'cancel'},{text:'Відключити',style:'destructive',onPress:()=>void run(async()=>{await apiFetch(`/integrations/${c.id}/`,{method:'DELETE'});setSelected(null);await load();})}]))}</View>}</View>)}
    {history&&<View style={[s.card,{backgroundColor:panel}]}><Text style={[s.heading,{color:text}]}>Історія синхронізації</Text>{history.runs.map(r=><Text key={r.id} style={{color:text}}>{new Date(r.started_at).toLocaleString()} · {r.error_code?'Потрібна увага':'Завершено'}</Text>)}{history.conflicts.map(c=><View key={c.id}><Text style={{color:text}}>Конфлікт: {c.conflict.fields.map(k=>conflictLabels[k]||k).join(', ')}</Text><Text style={{color:text}}>Flowi: {conflictText(c.conflict.local,c.conflict.fields)}</Text><Text style={{color:text}}>Зовнішня зміна: {conflictText(c.conflict.remote,c.conflict.fields)}</Text><View style={s.row}>{[{choice:'local',label:'Зберегти зміну Flowi'},{choice:'remote',label:'Прийняти зовнішню зміну'}].filter(x=>x.choice==='local'||!c.conflict.fields.includes('deadline')).map(x=>button(x.label,()=>void run(async()=>{await apiFetch(`/integrations/${history.connection.id}/conflicts/${c.id}/resolve/`,{method:'POST',body:{choice:x.choice}});setHistory(null);await load();})))}</View></View>)}</View>}
    {settings&&selected&&<View style={[s.card,{backgroundColor:panel}]}><Text style={[s.heading,{color:text}]}>{selected.label}: оберіть джерело</Text><View style={s.row}>{available.map(a=>button(a.label,()=>void run(async()=>{const r=await apiFetch<{source:string;schema:Schema;config:Partial<Config>}>(`/integrations/${selected.id}/sources/`,{method:'POST',body:{external_id:a.id}});setSourceId(r.source);setSchema(r.schema);setPreview(null);setConfig(c=>({...c,...r.config}));})))}</View>
      {schema&&<>{!calendar?<><Text style={{color:text}}>Отримувати завдання</Text><View style={s.row}>{button('Лише мої',()=>patch({scope:'mine'}),config.scope==='mine')}{button('Усі доступні',()=>patch({scope:'all'}),config.scope==='all')}</View>{['notion','worksection'].includes(selected.provider)&&input('Мій ідентифікатор у сервісі',config.externalUserId,v=>patch({externalUserId:v}))}
      {schema.fields.length>0&&['title','status','assignee','deadline','description','parent'].map(key=><View key={key}><Text style={{color:text}}>Поле: {{title:'Назва',status:'Статус',assignee:'Виконавець',deadline:'Дедлайн',description:'Опис',parent:'Батьківське завдання'}[key]}</Text><View style={s.row}>{schema.fields.map(f=>button(f.id,()=>patch({fields:{...config.fields,[key]:f.id},...(key==='status'?{statusType:f.type}:{})}),config.fields[key]===f.id))}</View></View>)}
      {schema.statuses.filter(x=>!x.field||x.field===config.fields.status).map(x=><View key={x.id}><Text style={{color:text}}>{x.label} → Flowi</Text><View style={s.row}>{statusOptions.map(t=>button(t.label,()=>patch({statusMap:{...config.statusMap,[x.id]:t.id}}),config.statusMap[x.id]===t.id))}</View></View>)}
      {statusOptions.map(x=><View key={x.id}><Text style={{color:text}}>Flowi «{x.label}» → зовнішній статус</Text><View style={s.row}>{schema.statuses.filter(t=>!t.field||t.field===config.fields.status).map(t=>button(t.label,()=>patch({writeMap:{...config.writeMap,[x.id]:t.id}}),config.writeMap[x.id]===t.id))}</View></View>)}
      {selected.provider==='worksection'&&<Text style={{color:text}}>Worksection передає активний і завершений статус. «У процесі» зберігається у Flowi; для нього оберіть активний зовнішній статус.</Text>}
      {button('Також завершені завдання',()=>patch({includeCompleted:!config.includeCompleted}),config.includeCompleted)}
      </>:<>{input('Днів у минулому',String(config.pastDays),v=>patch({pastDays:Number(v)}))}{input('Днів у майбутньому',String(config.futureDays),v=>patch({futureDays:Number(v)}))}<View style={s.row}>{[{id:'meetings',label:'Зустрічі'},{id:'planned_tasks',label:'Заплановані завдання'},{id:'deadlines',label:'Дедлайни'}].map(x=>button(x.label,()=>patch({exports:config.exports.includes(x.id)?config.exports.filter(v=>v!==x.id):[...config.exports,x.id]}),config.exports.includes(x.id)))}</View></>}
      {projectId&&assignees.length>0&&<View><Text style={{color:text}}>Зіставте виконавців з учасниками проєкту</Text>{assignees.map(id=><View key={id}><Text style={{color:text}}>Виконавець {id}</Text><View style={s.row}>{button('Не призначено',()=>patch({assignees:{...config.assignees,[id]:''}}),!config.assignees[id])}{listing?.members?.map(m=>button(m.label,()=>patch({assignees:{...config.assignees,[id]:m.id}}),config.assignees[id]===m.id))}</View></View>)}</View>}
      {button('Попередній перегляд',()=>void run(async()=>{const result=await apiFetch<NonNullable<typeof preview>>(`/integrations/${selected.id}/sources/${sourceId}/preview/`,{method:'POST',body:{config}});setPreview(result);setAssignees(result.assignees);}))}</>}
      {preview&&<><Text style={[s.heading,{color:text}]}>Попередній перегляд · {preview.count} записів</Text><Text style={{color:text}}>Дані ще не перенесено.</Text>{preview.items.map(x=><Text key={x.id} style={{color:text}}>{x.title}</Text>)}{preview.outbound.length>0&&<Text style={{color:text}}>Буде передано в зовнішній календар: {preview.outbound.map(x=>x.title).join(', ')}</Text>}{button('Підтвердити й запустити',()=>void run(async()=>{await apiFetch(`/integrations/${selected.id}/sources/${sourceId}/confirm/`,{method:'POST',body:{token:preview.token}});setSelected(null);setPreview(null);await load();setNotice('Джерело підключено.');}))}</>}
    </View>}
  </ScrollView>;
}
const s=StyleSheet.create({root:{padding:20,gap:16,paddingBottom:100,flexGrow:1},title:{fontSize:26,fontWeight:'700'},heading:{fontSize:17,fontWeight:'600'},card:{padding:16,borderRadius:16,gap:12,width:'100%',maxWidth:850,alignSelf:'center'},row:{flexDirection:'row',flexWrap:'wrap',gap:8},button:{paddingHorizontal:14,paddingVertical:12,borderRadius:10,minHeight:44,justifyContent:'center'},input:{borderWidth:1,borderRadius:10,padding:12,minHeight:44},field:{gap:6},error:{color:'#d83450'}});
