import React,{useState} from 'react';
import {Text,View,TouchableOpacity} from 'react-native';
import {LinearGradient} from 'expo-linear-gradient';
import type {Project} from '@/app/projects';
import {updateSynced} from '@/store/synced-storage';
import {projectAppearance,validColor,DEFAULT_APPEARANCE,type ProjectPalette} from '@/utils/projectAppearance';
import {TeamButton,TeamInput} from './TeamTaskPanel';
const COLORS=['#EF4444','#F97316','#F59E0B','#84CC16','#10B981','#0EA5E9','#7C3AED','#EC4899','#FCA5A5','#FDBA74','#FDE047','#BEF264','#6EE7B7','#7DD3FC','#C4B5FD','#F9A8D4','#B91C1C','#C2410C','#A16207','#4D7C0F','#047857','#0369A1','#8B5CF6','#BE185D','#FFFFFF','#CBD5E1','#64748B','#334155','#171717','#92400E','#14B8A6','#6366F1'];
function ColorField({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){const [width,setWidth]=useState(1);return <View style={{gap:6}}><TeamInput label={label+' · HEX'} value={value} onChange={onChange}/><View accessibilityLabel={label+' · спектр'} onLayout={e=>setWidth(e.nativeEvent.layout.width)} onStartShouldSetResponder={()=>true} onResponderGrant={e=>{const h=Math.max(0,Math.min(5.999,e.nativeEvent.locationX/width*6)),x=1-Math.abs(h%2-1),rgb=h<1?[1,x,0]:h<2?[x,1,0]:h<3?[0,1,x]:h<4?[0,x,1]:h<5?[x,0,1]:[1,0,x];onChange('#'+rgb.map(n=>Math.round(n*255).toString(16).padStart(2,'0')).join(''));}}><LinearGradient colors={['#ff0000','#ffff00','#00ff00','#00ffff','#0000ff','#ff00ff','#ff0000']} start={{x:0,y:0}} end={{x:1,y:0}} style={{height:44,borderRadius:8}}/></View></View>;}
export function ProjectAppearanceForm({project,canEdit,textColor}:{project:Project;canEdit:boolean;textColor:string}){
 const [appearance,setAppearance]=useState(()=>projectAppearance(project.appearance)),[color,setColor]=useState(project.color),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 if(!canEdit)return null;
 return <View style={{gap:12,paddingVertical:20}}><Text style={{color:textColor,fontSize:18,fontWeight:'700'}}>Вигляд проєкту</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{COLORS.map(hex=><TouchableOpacity key={hex} accessibilityRole="button" accessibilityLabel={`Колір ${hex}`} onPress={()=>setColor(hex)} style={{width:36,height:36,borderRadius:18,backgroundColor:hex,borderWidth:color.toLowerCase()===hex.toLowerCase()?3:1,borderColor:textColor}}/>)}</View><ColorField label="Позначка проєкту" value={color} onChange={setColor}/>{(['light','dark'] as const).map(mode=><View key={mode} style={{gap:10}}><Text style={{color:textColor,fontWeight:'700'}}>{mode==='light'?'Світла тема':'Темна тема'}</Text>{(['background','surface','accent'] as (keyof ProjectPalette)[]).map((field,i)=><ColorField key={field} label={['Фон','Поверхні','Акцент'][i]} value={appearance[mode][field]} onChange={value=>setAppearance({...appearance,[mode]:{...appearance[mode],[field]:value}})}/>)}</View>)}{!!message&&<Text accessibilityRole="alert" style={{color:textColor}}>{message}</Text>}<TeamButton label="Відновити палітри Flowi" onPress={()=>setAppearance(DEFAULT_APPEARANCE)}/><TeamButton label="Зберегти вигляд" disabled={busy} onPress={()=>{if(!validColor(color)||Object.values(appearance).some(p=>Object.values(p).some(v=>!validColor(v)))){setMessage('Введіть колір у форматі #RRGGBB');return;}setBusy(true);void updateSynced<Project>('projects',rows=>rows.map(p=>p.id===project.id?{...p,color,appearance}:p)).then(()=>setMessage('Вигляд збережено')).catch(e=>setMessage(String(e))).finally(()=>setBusy(false));}}/></View>;
}
