import React,{useState} from 'react';
import {Text,View,ScrollView,Modal} from 'react-native';
import {useRouter} from 'expo-router';
import {useAuth} from '@/store/auth';
import {useI18n} from '@/store/i18n';
import {useProjectRole} from '@/hooks/use-project-role';
import {useColorScheme} from '@/hooks/use-color-scheme';
import {CommentsSection} from '@/components/shared/CommentsSection';
import {isLead,teamPreferencesId,type TeamPreferences,type Discussion} from '@/utils/teamwork';
import type {Task} from '@/utils/taskUtils';
import {useProjectRecords,saveProjectRecord} from './useProjectRecords';
import {TeamButton,TeamInput} from './TeamTaskPanel';
import {projectShellColors} from './ProjectScreenShell';
export function ProjectDiscussions({projectId,initialId}:{projectId:string;initialId?:string}){
 const {user}=useAuth(),uid=String(user?.id??''),role=useProjectRole(projectId),router=useRouter(),{tr,lang}=useI18n(),dark=useColorScheme()==='dark',c=projectShellColors(dark,'#7C3AED');
 const prefs=useProjectRecords<TeamPreferences>('team_preferences').find(p=>p.projectId===projectId&&p.userId===uid);
 const rooms=useProjectRecords<Discussion>('discussions').filter(d=>d.projectId===projectId),tasks=useProjectRecords<Task>('tasks').filter(t=>t.projectId===projectId&&!t.backlogKind);
 const [selected,setSelected]=useState(initialId??''),[filter,setFilter]=useState('all'),[search,setSearch]=useState(''),[draft,setDraft]=useState<Discussion|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const room=rooms.find(d=>d.id===selected),canManage=!!room&&(isLead(role)||room.authorId===uid)&&role!=='viewer';
 async function run(fn:()=>Promise<unknown>){setError('');setBusy(true);try{await fn();}catch(e){setError(String(e));}finally{setBusy(false);}}
 return <View style={{gap:12}}><TeamInput label="Пошук обговорень" value={search} onChange={setSearch}/><ScrollView horizontal contentContainerStyle={{gap:6}}>{[['all','Усі'],['topic','Топіки'],['chat','Чати'],['archive','Архів']].map(([key,label])=><TeamButton key={key} label={(filter===key?'✓ ':'')+label} onPress={()=>setFilter(key)}/>)}</ScrollView>{role!=='viewer'&&<TeamButton label="Нове обговорення" onPress={()=>setDraft({id:`discussion-${Date.now()}`,projectId,title:'',body:'',kind:'topic',authorId:uid,createdAt:new Date().toISOString(),taskIds:[]})}/>}
 {!!error&&<Text accessibilityRole="alert" style={{color:'#DB4444'}}>{error}</Text>}
 {rooms.filter(d=>(filter==='archive'?!!d.archivedAt:!d.archivedAt&&(filter==='all'||(d.kind??'topic')===filter))&&`${d.title} ${d.body}`.toLowerCase().includes(search.toLowerCase())).map(d=><TeamButton key={d.id} label={(d.kind==='chat'?'Чат · ':'Топік · ')+d.title} onPress={()=>setSelected(d.id)}/>)}
 {room&&<View style={{gap:10,borderWidth:1,borderColor:c.border,borderRadius:12,padding:12}}><Text style={{color:c.text,fontWeight:'700',fontSize:20}}>{room.title}</Text><Text style={{color:c.text}}>{room.body}</Text><TeamButton label={prefs?.watchedDiscussionIds?.includes(room.id)?'Не стежити':'Стежити'} onPress={()=>void run(()=>saveProjectRecord('team_preferences',{...prefs,id:teamPreferencesId(projectId,uid),projectId,userId:uid,watchedDiscussionIds:prefs?.watchedDiscussionIds?.includes(room.id)?prefs.watchedDiscussionIds.filter(id=>id!==room.id):[...(prefs?.watchedDiscussionIds??[]),room.id]}))}/>{(room.taskIds??[]).map(id=><TeamButton key={id} label={tasks.find(t=>t.id===id)?.title??'Завдання'} onPress={()=>router.push({pathname:'/(tabs)',params:{open:id}} as never)}/>)}{canManage&&<><TeamButton label="Редагувати обговорення" onPress={()=>setDraft({...room})}/><TeamButton disabled={busy} label={room.archivedAt?'Відновити обговорення':'Архівувати обговорення'} onPress={()=>void run(()=>saveProjectRecord('discussions',{...room,archivedAt:room.archivedAt?undefined:new Date().toISOString()}))}/>{!room.archivedAt&&<TeamButton disabled={busy} label="Створити завдання з теми" onPress={()=>void run(async()=>{const task:Task={id:`topic-task-${Date.now()}`,projectId,title:room.title,description:room.body,status:'active',subtasks:[],createdAt:new Date().toISOString(),createdBy:uid};await saveProjectRecord('tasks',task);await saveProjectRecord('discussions',{...room,taskIds:[...(room.taskIds??[]),task.id]});})}/>}</>}
 <CommentsSection key={room.id} projectId={projectId} targetType="discussion" targetId={room.id} isOwner={role==='owner'&&!room.archivedAt} currentUserId={role==='viewer'||room.archivedAt?null:uid} colors={c} isDark={dark} locale={lang} tr={tr}/></View>}
 <Modal visible={!!draft} animationType="slide" onRequestClose={()=>setDraft(null)}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{padding:24,paddingTop:60,paddingBottom:80,gap:12,backgroundColor:c.bg1}}>{draft&&<><TeamInput label="Назва обговорення" value={draft.title} onChange={v=>setDraft({...draft,title:v})}/><TeamInput label="Опис" value={draft.body} onChange={v=>setDraft({...draft,body:v})} multiline/><View style={{flexDirection:'row',gap:8}}>{(['topic','chat'] as const).map(kind=><TeamButton key={kind} label={(draft.kind===kind?'✓ ':'')+(kind==='topic'?'Топік':'Чат')} onPress={()=>setDraft({...draft,kind})}/>)}</View><Text style={{color:c.text}}>Пов’язані завдання</Text>{tasks.map(t=><TeamButton key={t.id} label={(draft.taskIds?.includes(t.id)?'✓ ':'')+t.title} onPress={()=>setDraft({...draft,taskIds:draft.taskIds?.includes(t.id)?draft.taskIds.filter(id=>id!==t.id):[...(draft.taskIds??[]),t.id]})}/>)}<TeamButton label="Зберегти" disabled={busy||!draft.title.trim()} onPress={()=>void run(async()=>{await saveProjectRecord('discussions',{...draft,title:draft.title.trim(),updatedAt:new Date().toISOString()});setSelected(draft.id);setDraft(null);})}/><TeamButton label="Закрити" onPress={()=>setDraft(null)}/></>}</ScrollView></Modal>
 </View>;
}
