import React,{useState} from 'react';
import {ScrollView,Text,View,TouchableOpacity,Modal,useWindowDimensions} from 'react-native';
import {useLocalSearchParams,useRouter} from 'expo-router';
import {useProject} from '@/hooks/use-project';
import {useProjectRole} from '@/hooks/use-project-role';
import {useColorScheme} from '@/hooks/use-color-scheme';
import {ProjectScreenShell,projectShellColors} from '@/components/projects/ProjectScreenShell';
import {TeamButton} from '@/components/projects/TeamTaskPanel';
import {useProjectRecords} from '@/components/projects/useProjectRecords';
import {calendarSprintSegments} from '@/utils/calendarSprints';
import {expandMeetings,type Meeting} from '@/utils/meetings';
import type {Task} from '@/utils/taskUtils';
import type {Sprint} from '@/utils/sprintUtils';
const key=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function cells(d:Date){const start=new Date(d.getFullYear(),d.getMonth(),1);start.setDate(start.getDate()-(start.getDay()+6)%7);return Array.from({length:42},(_,i)=>new Date(start.getFullYear(),start.getMonth(),start.getDate()+i));}
export default function ProjectCalendar(){
 const {id}=useLocalSearchParams<{id:string}>(),router=useRouter(),{project}=useProject(id),role=useProjectRole(id),{width}=useWindowDimensions();
 const dark=useColorScheme()==='dark',c=projectShellColors(dark,project?.color??'#7C3AED',project?.appearance);
 const tasks=useProjectRecords<Task>('tasks').filter(t=>t.projectId===id&&!t.backlogKind),meetings=useProjectRecords<Meeting>('meetings').filter(m=>m.projectId===id),sprints=useProjectRecords<Sprint>('sprints');
 const [mode,setMode]=useState<'week'|'month'|'quarter'|'year'>('month'),[anchor,setAnchor]=useState(new Date()),[selected,setSelected]=useState<string|null>(null);
 const periods=Array.from({length:mode==='year'?12:mode==='quarter'?3:1},(_,i)=>new Date(anchor.getFullYear(),(mode==='year'?0:anchor.getMonth())+i,1));
 const start=new Date(anchor);start.setDate(start.getDate()-(start.getDay()+6)%7);const week=Array.from({length:7},(_,i)=>new Date(start.getFullYear(),start.getMonth(),start.getDate()+i));
 const dates=mode==='week'?week:periods.flatMap(cells),occurrences=expandMeetings(meetings,dates[0],dates[dates.length-1]);
 const dayTasks=(day:string)=>tasks.filter(t=>t.deadline&&key(new Date(t.deadline))===day),dayMeetings=(day:string)=>occurrences.filter(m=>m.date===day);
 const entries=(day:string)=><View style={{gap:6}}>{dayMeetings(day).map(m=><TeamButton key={`${m.id}-${m.date}`} label={`Зустріч · ${m.time} · ${m.title}`} onPress={()=>router.push({pathname:'/project/[id]/meetings',params:{id,open:m._origId??m.id}} as never)}/>)}{dayTasks(day).map(t=><TeamButton key={t.id} label={`Завдання · ${t.title}`} onPress={()=>router.push({pathname:'/(tabs)',params:{open:t.id}} as never)}/>)}{!dayMeetings(day).length&&!dayTasks(day).length&&<Text style={{color:c.sub}}>Немає записів</Text>}</View>;
 return <ProjectScreenShell project={project} isDark={dark} title="Календар"><ScrollView contentContainerStyle={{padding:16,paddingBottom:120,gap:12}}>
 <View style={{flexDirection:'row',flexWrap:'wrap',gap:6}}>{(['week','month','quarter','year'] as const).map((m,i)=><TeamButton key={m} label={(mode===m?'✓ ':'')+['Тиждень','Місяць','3 місяці','Рік'][i]} onPress={()=>setMode(m)}/>)}</View>
 <Text style={{color:c.text,fontWeight:'700'}}>{mode==='week'?`${key(week[0])} — ${key(week[6])}`:anchor.toLocaleDateString('uk-UA',{month:'long',year:'numeric'})}</Text>
 <View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{[-1,1].map(n=><TeamButton key={n} label={n===-1?'Попередній період':'Наступний період'} onPress={()=>setAnchor(mode==='week'?new Date(anchor.getFullYear(),anchor.getMonth(),anchor.getDate()+n*7):new Date(anchor.getFullYear(),anchor.getMonth()+n*(mode==='year'?12:mode==='quarter'?3:1),1))}/>)}<TeamButton label="Сьогодні" onPress={()=>setAnchor(new Date())}/></View>
 {mode==='week'?week.map(d=><View key={key(d)} style={{borderWidth:1,borderColor:c.border,borderRadius:12,padding:12,gap:8}}>{calendarSprintSegments(sprints,id,[key(d)]).map(s=><Text key={s.sprint.id} style={{backgroundColor:c.accent,color:'#fff',padding:4}}>№{s.number} · {s.sprint.name}</Text>)}<Text style={{color:c.text,fontWeight:'700'}}>{d.toLocaleDateString('uk-UA',{weekday:'long'})}</Text>{entries(key(d))}<TeamButton label={d.toLocaleDateString('uk-UA')} onPress={()=>setSelected(key(d))}/></View>):<View style={{flexDirection:'row',flexWrap:'wrap',gap:12}}>{periods.map(period=><View key={key(period)} style={{width:width>=1000&&mode!=='month'?'48%':'100%',gap:8}}><Text style={{color:c.text,fontWeight:'700'}}>{period.toLocaleDateString('uk-UA',{month:'long',year:'numeric'})}</Text><View style={{flexDirection:'row'}}>{['Пн','Вт','Ср','Чт','Пт','Сб','Нд'].map(d=><Text key={d} style={{width:'14.285%',textAlign:'center',color:c.sub}}>{d}</Text>)}</View><View style={{flexDirection:'row',flexWrap:'wrap'}}>{cells(period).map(d=>{const day=key(d),inMonth=d.getMonth()===period.getMonth();return <TouchableOpacity key={day} disabled={!inMonth&&mode!=='month'} accessibilityRole="button" accessibilityLabel={`${day}, завдань ${dayTasks(day).length}, зустрічей ${dayMeetings(day).length}`} onPress={()=>setSelected(day)} style={{width:'14.285%',minHeight:mode==='year'?48:82,padding:2,opacity:inMonth?1:mode==='month'?.4:0}}><View style={{flex:1,borderWidth:1,borderColor:c.border,borderRadius:6,overflow:'hidden',padding:2}}>{calendarSprintSegments(sprints,id,[day]).map(s=><Text key={s.sprint.id} numberOfLines={1} style={{backgroundColor:c.accent,color:'#fff',fontSize:10}}>№{s.number}</Text>)}<View style={{flex:1}}/><Text style={{color:c.accent,fontSize:10}}>{dayTasks(day).length?`● ${dayTasks(day).length}`:''}{dayMeetings(day).length?' ▪':''}</Text><Text style={{color:c.text,fontSize:12}}>{d.getDate()}</Text></View></TouchableOpacity>;})}</View></View>)}</View>}
 </ScrollView><Modal visible={!!selected} animationType="slide" onRequestClose={()=>setSelected(null)}><ScrollView contentContainerStyle={{padding:24,paddingTop:60,paddingBottom:80,gap:12,backgroundColor:c.bg1}}><Text style={{color:c.text,fontSize:22}}>{selected}</Text>{selected&&entries(selected)}{role!=='viewer'&&<><TeamButton label="Додати завдання" onPress={()=>{router.push({pathname:'/(tabs)',params:{create:'1',projectId:id,deadline:selected}} as never);setSelected(null);}}/><TeamButton label="Додати зустріч" onPress={()=>{router.push({pathname:'/project/[id]/meetings',params:{id,create:'1',date:selected}} as never);setSelected(null);}}/></>}<TeamButton label="Закрити" onPress={()=>setSelected(null)}/></ScrollView></Modal></ProjectScreenShell>;
}
